server:
  port: 8080

spring:
  application:
     name: discount-service

  data:
   mongodb:
        host: ${MONGODB_HOST:localhost}
        port: ${MONGODB_PORT:27018}
        username: ${MONGODB_USERNAME:root}
        password: ${MONGODB_PASSWORD:secret}
        database: ${MONGODB_DATABASE:discount}
        auto-index-creation: ${MONGODB_AUTO_INDEX_CREATION:true}
        authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}