server:
  port: ${APP_SERVER_PORT:8085}

spring:
  application:
     name: discount-service

  data:
   mongodb:
        host: ${MONGODB_HOST:localhost}
        port: ${MONGODB_PORT:27018}
        username: ${MONGODB_USERNAME:root}
        password: ${MONGODB_PASSWORD:secret}
        database: ${MONGODB_DATABASE:discount}
        auto-index-creation: ${MONGODB_AUTO_INDEX_CREATION:true}
        authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}

keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/discount-realm}
  realm: ${KEYCLOAK_REALM:discount-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:discount}